# Site settings
title: Tom Hrabchak
email: thrabchak@gmail.com
description: >
  My small personal website.

baseurl: "" # the subpath of your site, e.g. /blog

facebook_username: thrabchak
twitter_username:  thrabchak
github_username:   thrabchak
timezone: EST

# Build settings
markdown: kramdown
